# Generated by Django 4.2.29 on 2026-03-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Sex', 'verbose_name_plural': 'Sex'},
        ),
    ]
