# Generated by Django 4.2.29 on 2026-03-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_alter_sex_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ID Type',
                'verbose_name_plural': 'ID Types',
                'ordering': ['id'],
            },
        ),
    ]
