# Generated by Django 4.2.29 on 2026-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0005_educationlevel_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
