# Generated by Django 4.2.29 on 2026-03-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_occupation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='code',
            new_name='value',
        ),
    ]
