# Generated by Django 4.2.29 on 2026-03-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0008_occupation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtype',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='idtype',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
