# Generated by Django 4.2.29 on 2026-03-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0009_idtype_value_alter_idtype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'YesNo',
                'verbose_name_plural': 'YesNo',
            },
        ),
        migrations.CreateModel(
            name='YesNoNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'YesNoNA',
                'verbose_name_plural': 'YesNoNA',
            },
        ),
        migrations.CreateModel(
            name='YesNoUnk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'YesNoUnk',
                'verbose_name_plural': 'YesNoUnk',
            },
        ),
    ]
