# Generated by Django 4.2.29 on 2026-03-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0018_visitday_visitscheduleconfig_missedvisitreason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitScheduleConfig',
        ),
    ]
