# Generated by Django 4.2.29 on 2026-03-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0022_donenotdone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donenotdone',
            options={'verbose_name': 'DoneNotDone', 'verbose_name_plural': 'DoneNotDones'},
        ),
    ]
