# Generated by Django 4.2.29 on 2026-04-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herbal', '0164_visitschedule_last_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('3_day', '3 Days Before'), ('1_day', '1 Day Before'), ('same_day', 'Same Day'), ('overdue', 'Overdue Weekly')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='herbal.visitschedule')),
            ],
            options={
                'unique_together': {('visit', 'reminder_type')},
            },
        ),
    ]
