# Generated by Django 4.2.20 on 2025-08-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanual',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
