# Generated by Django 4.2.29 on 2026-03-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0002_enrollment_created_at_enrollment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='subject',
        ),
        migrations.AddField(
            model_name='visit',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits_enrollment', to='herbal.enrollment'),
            preserve_default=False,
        ),
    ]
