# Generated by Django 4.2.29 on 2026-03-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0004_crf1_created_at_crf1_created_by_crf1_delete_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='subject',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='screening',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='herbal.screening'),
            preserve_default=False,
        ),
    ]
