# Generated by Django 4.2.29 on 2026-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0005_remove_enrollment_subject_enrollment_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='missed_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
