# Generated by Django 4.2.29 on 2026-03-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0007_dataquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf6',
            name='reason',
            field=models.CharField(choices=[('completed', 'Completed Study'), ('ltf', 'Lost To Follow Up'), ('withdrawn', 'Participant Withdrew'), ('transfer_out', 'Transferred Out'), ('medical_reason', 'Medical Reason')], max_length=50),
        ),
    ]
