# Generated by Django 4.2.29 on 2026-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0008_alter_crf6_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='missed_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='missed_reason',
            field=models.CharField(blank=True, choices=[('patient_unavailable', 'Patient Unavailable'), ('patient_refused', 'Patient Refused'), ('transport_issue', 'Transport Issue'), ('site_error', 'Site Error'), ('medical_reason', 'Medical Reason'), ('changed_region', 'Changed Region'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
