# Generated by Django 4.2.29 on 2026-03-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0009_visitschedule_missed_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unscheduledvisit',
            name='after_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unscheduled_after', to='herbal.visitschedule'),
        ),
        migrations.AlterField(
            model_name='unscheduledvisit',
            name='reason',
            field=models.CharField(choices=[('ae', 'Adverse Event'), ('unscheduled_followup', 'Unscheduled Follow-up'), ('protocol_deviation', 'Protocol Deviation'), ('missed_visit_followup', 'Missed Visit Follow-up'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='missed_reason',
            field=models.CharField(blank=True, choices=[('patient_unavailable', 'Patient Unavailable'), ('patient_refused', 'Patient Refused'), ('transport_issue', 'Transport Issue'), ('site_error', 'Site Error'), ('medical_reason', 'Medical Reason'), ('changed_location', 'Changed Location'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
