# Generated by Django 4.2.29 on 2026-03-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0010_unscheduledvisit_after_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='after_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_after', to='herbal.visitschedule'),
        ),
    ]
