# Generated by Django 4.2.29 on 2026-03-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0011_crf5_after_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('incomplete', 'Incomplete'), ('na', 'Not Applicable')], default='pending', max_length=20),
        ),
    ]
