# Generated by Django 4.2.29 on 2026-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0012_alter_visitschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
