# Generated by Django 4.2.29 on 2026-03-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0001_initial'),
        ('herbal', '0013_alter_subject_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='phone',
            new_name='other_phone',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='date_of_birth',
            new_name='reg_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='village',
        ),
        migrations.AddField(
            model_name='subject',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='hid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='id_type',
            field=models.CharField(blank=True, choices=[('NIDA', 'NIDA'), ('VOTER', 'Voter ID'), ('PASSPORT', 'Passport'), ('LICENSE', 'DRIVING LICENSE'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='idn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('widowed', 'Widowed/Widower'), ('cohabit', 'Cohabit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='choices.sex'),
        ),
    ]
