# Generated by Django 4.2.29 on 2026-03-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0005_educationlevel_occupation'),
        ('herbal', '0014_rename_phone_subject_other_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.educationlevel'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.idtype'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.occupation'),
        ),
    ]
