# Generated by Django 4.2.29 on 2026-03-18 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('herbal', '0015_alter_subject_education_level_alter_subject_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.ward'),
        ),
    ]
