# Generated by Django 4.2.29 on 2026-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0016_alter_subject_district_alter_subject_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
