# Generated by Django 4.2.29 on 2026-03-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0017_subject_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='hid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
