# Generated by Django 4.2.29 on 2026-03-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0019_alter_subject_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
