# Generated by Django 4.2.29 on 2026-03-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0020_alter_subject_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='other_occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
