# Generated by Django 4.2.29 on 2026-03-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0021_subject_other_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='id_type',
            new_name='identification_type',
        ),
    ]
