# Generated by Django 4.2.29 on 2026-03-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0022_rename_id_type_subject_identification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='other_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
