# Generated by Django 4.2.29 on 2026-03-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0023_subject_other_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='age_eligible',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='comments',
        ),
        migrations.AddField(
            model_name='screening',
            name='age_18',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='biopsy',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='brain_cancer',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='breast_cancer',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='breast_feeding',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='cervical_cancer',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='ckd',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='consented',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='consented_nimregenin',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='liver_disease',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='nimregenin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='pregnant',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='prostate_cancer',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
