# Generated by Django 4.2.29 on 2026-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0024_remove_screening_age_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='breast_feeding',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='cervical_cancer',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='pregnant',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='prostate_cancer',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
    ]
