# Generated by Django 4.2.29 on 2026-03-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0025_alter_screening_breast_feeding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='consented',
            new_name='consent',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='consented_nimregenin',
            new_name='consent_nimregenin',
        ),
        migrations.RenameField(
            model_name='screening',
            old_name='reasons',
            new_name='consent_reasons',
        ),
        migrations.AddField(
            model_name='screening',
            name='nimregenin_reasons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
