# Generated by Django 4.2.29 on 2026-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0026_rename_consented_screening_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='consent_nimregenin',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'NA')]),
        ),
    ]
