# Generated by Django 4.2.29 on 2026-03-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0010_yesno_yesnona_yesnounk'),
        ('herbal', '0027_alter_screening_consent_nimregenin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='consent_nimregenin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.yesnounk'),
        ),
    ]
