# Generated by Django 4.2.29 on 2026-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0028_alter_screening_consent_nimregenin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='consent_signed',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_by',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cycle_number',
            field=models.PositiveIntegerField(default=1, help_text='Current cycle number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='previous_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pt_category',
            field=models.CharField(choices=[('intervention', 'Intervention'), ('control', 'Control')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pt_type',
            field=models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow Up')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_cycle',
            field=models.PositiveIntegerField(default=1, help_text='Total planned treatment cycles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='treatment_type',
            field=models.CharField(choices=[('chemo', 'Chemotherapy'), ('radiation', 'Radiation'), ('surgery', 'Surgery'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
