# Generated by Django 4.2.29 on 2026-03-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0029_remove_enrollment_consent_signed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='remarks',
            field=models.TextField(blank=tuple, null=True),
        ),
    ]
