# Generated by Django 4.2.29 on 2026-03-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_label'),
        ('herbal', '0030_remove_enrollment_status_enrollment_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cancer Type',
                'verbose_name_plural': 'Cancer Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_enrollment', models.PositiveIntegerField()),
                ('cancer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbal.cancertype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'unique_together': {('site', 'cancer_type')},
            },
        ),
    ]
