# Generated by Django 4.2.29 on 2026-03-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0031_cancertype_studytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='cancer_types',
            field=models.ManyToManyField(blank=True, related_name='screening_cancer', to='herbal.cancertype'),
        ),
    ]
