# Generated by Django 4.2.29 on 2026-03-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0012_alter_patientcategory_options_and_more'),
        ('herbal', '0032_screening_cancer_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='pt_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_categories', to='choices.patientcategory'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='pt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_types', to='choices.patienttype'),
        ),
    ]
