# Generated by Django 4.2.29 on 2026-03-20 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0033_alter_enrollment_pt_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='treatment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_treatments', to='choices.treatmenttype'),
        ),
    ]
