# Generated by Django 4.2.29 on 2026-03-20 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0034_alter_enrollment_treatment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='previous_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_previous_treatment', to='choices.treatmenttype'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='treatment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
