# Generated by Django 4.2.29 on 2026-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0035_enrollment_previous_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='hid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='idn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
