# Generated by Django 4.2.29 on 2026-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0036_alter_subject_hid_alter_subject_idn'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='previous_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='treatment_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='remarks',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
