# Generated by Django 4.2.29 on 2026-03-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0037_enrollment_previous_other_enrollment_treatment_other_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf1',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='crf1',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='crf1',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='crf1',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='crf1',
            name='weight',
        ),
        migrations.AddField(
            model_name='crf1',
            name='asthma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_asthma', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='asthma_medicatn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_asthma_med', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='asthma_medicatn_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf1',
            name='chemotherapy_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_chemotherapy', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='diabetic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_diabetic', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='diabetic_medicatn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_diabetic_med', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='diabetic_medicatn_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf1',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf1',
            name='heart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_heart', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='heart_medicatn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_heart_med', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='heart_medicatn_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf1',
            name='hiv_aids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_hiv', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='hiv_aids_medicatn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_hiv_med', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='hiv_aids_medicatn_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf1',
            name='hypertension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_hypertension', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='hypertension_medicatn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_hypertension_med', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='hypertension_medicatn_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf1',
            name='nimregenin_herbal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_nimregenin', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='other_herbal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_other_herbal', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='other_medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_other_medical', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='radiotherapy_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_radiotherapy', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf1',
            name='surgery_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crf1_surgery', to='choices.yesnounk'),
        ),
    ]
