# Generated by Django 4.2.29 on 2026-03-20 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0038_rename_notes_crf1_remarks_remove_crf1_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf1',
            name='diagnosis_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
