# Generated by Django 4.2.29 on 2026-03-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0039_alter_crf1_diagnosis_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF1OtherMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_specify', models.CharField(max_length=255)),
                ('other_medicatn_name', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_medicals', to='herbal.crf1')),
                ('other_medical_medicatn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.yesnounk')),
            ],
        ),
    ]
