# Generated by Django 4.2.29 on 2026-03-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0040_crf1othermedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF1Nimregenin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimregenin_preparation', models.CharField(max_length=255)),
                ('nimregenin_start', models.DateField(blank=True, null=True)),
                ('nimregenin_end', models.DateField(blank=True, null=True)),
                ('nimregenin_dose', models.CharField(max_length=255)),
                ('nimregenin_frequency', models.CharField(max_length=255)),
                ('nimregenin_remarks', models.TextField(blank=True)),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nimregenins', to='herbal.crf1')),
                ('nimregenin_ongoing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='choices.yesnounk')),
            ],
        ),
    ]
