# Generated by Django 4.2.29 on 2026-03-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0041_crf1nimregenin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF1OtherHerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbal_preparation', models.CharField(max_length=255)),
                ('herbal_start', models.DateField()),
                ('herbal_end', models.DateField(blank=True, null=True)),
                ('herbal_dose', models.CharField(max_length=255)),
                ('herbal_frequency', models.CharField(max_length=255)),
                ('herbal_remarks', models.TextField(blank=True)),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_herbals', to='herbal.crf1')),
                ('herbal_ongoing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='choices.yesnounk')),
            ],
        ),
    ]
