# Generated by Django 4.2.29 on 2026-03-20 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0042_crf1otherherbal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF1Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery', models.CharField(max_length=255)),
                ('surgery_start', models.DateField()),
                ('surgery_number', models.IntegerField()),
                ('surgery_remarks', models.TextField(blank=True)),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='herbal.crf1')),
            ],
        ),
        migrations.CreateModel(
            name='CRF1Radiotherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiotherapy', models.CharField(max_length=255)),
                ('radiotherapy_start', models.DateField()),
                ('radiotherapy_end', models.DateField(blank=True, null=True)),
                ('radiotherapy_dose', models.CharField(max_length=255)),
                ('radiotherapy_frequency', models.CharField(max_length=255)),
                ('radiotherapy_remarks', models.TextField(blank=True)),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiotherapies', to='herbal.crf1')),
                ('radiotherapy_ongoing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='choices.yesnounk')),
            ],
        ),
        migrations.CreateModel(
            name='CRF1Chemotherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemotherapy', models.CharField(max_length=255)),
                ('chemotherapy_start', models.DateField()),
                ('chemotherapy_end', models.DateField(blank=True, null=True)),
                ('chemotherapy_dose', models.CharField(max_length=255)),
                ('chemotherapy_frequency', models.CharField(max_length=255)),
                ('chemotherapy_remarks', models.TextField(blank=True)),
                ('chemotherapy_ongoing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='choices.yesnounk')),
                ('crf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemotherapies', to='herbal.crf1')),
            ],
        ),
    ]
