# Generated by Django 4.2.29 on 2026-03-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0043_crf1surgery_crf1radiotherapy_crf1chemotherapy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf1othermedical',
            old_name='remarks',
            new_name='medication_remarks',
        ),
    ]
