# Generated by Django 4.2.29 on 2026-03-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0013_treatmenttype'),
        ('herbal', '0044_rename_remarks_crf1othermedical_medication_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='age_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='biopsy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='brain_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='breast_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='breast_feeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='cervical_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='ckd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='consent_nimregenin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='liver_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='pregnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='prostate_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
    ]
