# Generated by Django 4.2.29 on 2026-03-22 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0015_method_appearance'),
        ('herbal', '0046_alter_cancertype_options_cancertype_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf2',
            old_name='comments',
            new_name='abdominal_comments',
        ),
        migrations.RemoveField(
            model_name='crf2',
            name='lab_result',
        ),
        migrations.AddField(
            model_name='crf2',
            name='abdominal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='abdominal_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='appearance_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='appearance_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10, message='BMI too low'), django.core.validators.MaxValueValidator(80, message='BMI too high')]),
        ),
        migrations.AddField(
            model_name='crf2',
            name='cardiovascular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='cardiovascular_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='cardiovascular_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='crf2',
            name='endocrine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='endocrine_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='endocrine_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AddField(
            model_name='crf2',
            name='heent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='heent_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='heent_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(50, message='Height too low (min 50 cm)'), django.core.validators.MaxValueValidator(250, message='Height too high (max 250 cm)')]),
        ),
        migrations.AddField(
            model_name='crf2',
            name='local_examination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='local_examination_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='local_examination_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='lymphatic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='lymphatic_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='lymphatic_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.method'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='musculoskeletal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='musculoskeletal_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='musculoskeletal_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='neurological',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='neurological_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='neurological_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='phys_exm_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='physical_exams_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='physical_other_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='physical_other_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='physical_other_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf2',
            name='physical_other_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='physical_performed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='psychological',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='psychological_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='psychological_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='respiratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='respiratory_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='crf2',
            name='respiratory_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='skin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='skin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='skin_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='systolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='crf2',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(28, message='Temperature too low'), django.core.validators.MaxValueValidator(40, message='Temperature too high')]),
        ),
        migrations.AddField(
            model_name='crf2',
            name='urogenital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='urogenital_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='urogenital_signifcnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf2',
            name='vital_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf2',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(2, message='Weight too low'), django.core.validators.MaxValueValidator(300, message='Weight too high')]),
        ),
    ]
