# Generated by Django 4.2.29 on 2026-03-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0047_rename_comments_crf2_abdominal_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf2',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
