# Generated by Django 4.2.29 on 2026-03-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers'),
        ('herbal', '0048_crf2_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf2',
            name='physical_performed',
        ),
        migrations.AddField(
            model_name='crf2',
            name='physcl_pfmd_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'site__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile'),
        ),
    ]
