# Generated by Django 4.2.29 on 2026-03-25 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0015_method_appearance'),
        ('herbal', '0049_remove_crf2_physical_performed_crf2_physcl_pfmd_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRF2OtherPhysclExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(blank=True, max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('crf2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_physcl_exams', to='herbal.crf2')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.appearance')),
                ('signifcnt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.yesnounk')),
            ],
        ),
    ]
