# Generated by Django 4.2.29 on 2026-03-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0015_method_appearance'),
        ('herbal', '0050_crf2otherphysclexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='screening',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesno'),
        ),
        migrations.AddField(
            model_name='screening',
            name='reason_other',
            field=models.TextField(blank=True),
        ),
    ]
