# Generated by Django 4.2.29 on 2026-03-25 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0016_notenrolledreason'),
        ('herbal', '0051_screening_enrolled_screening_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.notenrolledreason'),
        ),
    ]
