# Generated by Django 4.2.29 on 2026-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0052_alter_screening_enrolled_alter_screening_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='reason_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
