# Generated by Django 4.2.29 on 2026-03-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0016_notenrolledreason'),
        ('herbal', '0053_screening_reason_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='breast_feeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='ckd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='liver_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='pregnant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
    ]
