# Generated by Django 4.2.29 on 2026-03-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0054_alter_screening_breast_feeding_alter_screening_ckd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='consent_reasons',
            new_name='consent_other',
        ),
    ]
