# Generated by Django 4.2.29 on 2026-03-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0055_rename_consent_reasons_screening_consent_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='consent_other',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
