# Generated by Django 4.2.29 on 2026-03-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0017_notconsetreason'),
        ('herbal', '0057_screening_consent_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='consent_reasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.notconsetreason'),
        ),
    ]
