# Generated by Django 4.2.29 on 2026-03-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0058_alter_screening_consent_reasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='nimregenin_reasons',
        ),
        migrations.AddField(
            model_name='screening',
            name='nimregenin_other',
            field=models.TextField(blank=True),
        ),
    ]
