# Generated by Django 4.2.29 on 2026-03-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0017_notconsetreason'),
        ('herbal', '0059_remove_screening_nimregenin_reasons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='nimregenin_reasons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.notconsetreason'),
        ),
    ]
