# Generated by Django 4.2.29 on 2026-03-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0017_notconsetreason'),
        ('herbal', '0060_screening_nimregenin_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='age_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='biopsy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='brain_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='breast_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='cervical_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='prostate_cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
    ]
