# Generated by Django 4.2.29 on 2026-03-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0018_visitday_visitscheduleconfig_missedvisitreason'),
        ('herbal', '0061_alter_screening_age_18_alter_screening_biopsy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='missed_reason_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.missedvisitreason'),
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='visit_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_schedules', to='choices.visitday'),
        ),
    ]
