# Generated by Django 4.2.29 on 2026-03-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0062_visitschedule_missed_reason_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitschedule',
            name='missed_reason_fk',
        ),
    ]
