# Generated by Django 4.2.29 on 2026-03-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0018_visitday_visitscheduleconfig_missedvisitreason'),
        ('herbal', '0064_visitschedule_missed_reason_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitschedule',
            name='missed_reason_fk',
        ),
        migrations.AlterField(
            model_name='visitschedule',
            name='missed_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='choices.missedvisitreason'),
        ),
    ]
