# Generated by Django 4.2.29 on 2026-03-26 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('choices', '0019_delete_visitscheduleconfig'),
        ('herbal', '0065_remove_visitschedule_missed_reason_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_days', models.IntegerField(help_text='Days from enrollment date')),
                ('window_before', models.IntegerField(default=3)),
                ('window_after', models.IntegerField(default=3)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='choices.visitday')),
            ],
            options={
                'ordering': ['visit_day__order'],
            },
        ),
    ]
