# Generated by Django 4.2.29 on 2026-03-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0066_visitscheduleconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='cycle_number',
            field=models.PositiveIntegerField(blank=True, help_text='Current cycle number', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='total_cycle',
            field=models.PositiveIntegerField(blank=True, help_text='Total planned treatment cycles', null=True),
        ),
    ]
