# Generated by Django 4.2.29 on 2026-03-27 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0067_alter_enrollment_cycle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf1chemotherapy',
            name='chemotherapy_dose',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crf1chemotherapy',
            name='chemotherapy_frequency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
