# Generated by Django 4.2.29 on 2026-03-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0068_alter_crf1chemotherapy_chemotherapy_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf1chemotherapy',
            name='chemotherapy_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
