# Generated by Django 4.2.29 on 2026-03-27 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0070_alter_crf1nimregenin_nimregenin_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf1otherherbal',
            name='herbal_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crf1otherherbal',
            name='herbal_frequency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='crf1radiotherapy',
            name='radiotherapy_dose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crf1radiotherapy',
            name='radiotherapy_frequency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
    ]
