# Generated by Django 4.2.29 on 2026-03-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0071_alter_crf1otherherbal_herbal_dose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf2',
            name='physical_other_comments',
        ),
        migrations.RemoveField(
            model_name='crf2',
            name='physical_other_signifcnt',
        ),
        migrations.RemoveField(
            model_name='crf2',
            name='physical_other_specify',
        ),
        migrations.RemoveField(
            model_name='crf2',
            name='physical_other_system',
        ),
    ]
