# Generated by Django 4.2.29 on 2026-03-28 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0019_delete_visitscheduleconfig'),
        ('herbal', '0072_remove_crf2_physical_other_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf3',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='crf3',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='crf3',
            name='adherence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adherence_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='adherence_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf3',
            name='backpain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backpain_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='blood_urine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_urine_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='convulsions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convulsions_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='diarrhoea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarrhoea_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='difficult_breathing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breathing_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='fatigue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatigue_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='fever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fever_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='headaches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headaches_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='heartburn_indigestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heartburn_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='herbal_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf3',
            name='herbal_medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herbal_medication_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='loss_appetite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_appetite_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='loss_consciousness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loss_consciousness_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='micturition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micturition_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='muscle_pain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muscle_pain_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='nausea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nausea_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='other_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf3',
            name='pv_bleeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_bleeding_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='pv_discharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_discharge_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='sore_throat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sore_throat_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='swelling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swelling_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='symptoms_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptoms_other_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='symptoms_other_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf3',
            name='vomiting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vomiting_crf3', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf3',
            name='weight_loss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_loss_crf3', to='choices.yesnounk'),
        ),
    ]
