# Generated by Django 4.2.29 on 2026-03-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0073_remove_crf3_severity_remove_crf3_symptoms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf3',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='crf3',
            name='other_comments',
        ),
    ]
