# Generated by Django 4.2.29 on 2026-03-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0019_delete_visitscheduleconfig'),
        ('herbal', '0074_rename_notes_crf3_remarks_remove_crf3_other_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf7',
            name='follow_up_needed',
        ),
        migrations.RemoveField(
            model_name='crf7',
            name='investigator_notes',
        ),
        migrations.AddField(
            model_name='crf7',
            name='anxiety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf7',
            name='cdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf7',
            name='cpersid',
            field=models.CharField(blank=True, help_text='Name of person entering data', max_length=150),
        ),
        migrations.AddField(
            model_name='crf7',
            name='fdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf7',
            name='mobility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf7',
            name='pain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf7',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf7',
            name='self_care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf7',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf7',
            name='usual_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
    ]
