# Generated by Django 4.2.29 on 2026-03-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0076_crf7_created_at_crf7_created_by_crf7_delete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf7',
            name='remark2',
            field=models.TextField(blank=True),
        ),
    ]
