# Generated by Django 4.2.29 on 2026-03-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0077_crf7_remark2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf7',
            name='remark2',
        ),
    ]
