# Generated by Django 4.2.29 on 2026-03-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0078_remove_crf7_remark2'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf7',
            name='remarks2',
            field=models.TextField(blank=True),
        ),
    ]
