# Generated by Django 4.2.29 on 2026-03-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0079_crf7_remarks2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf7',
            name='remarks2',
        ),
    ]
