# Generated by Django 4.2.29 on 2026-03-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0080_remove_crf7_remarks2'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf7',
            name='qui',
            field=models.TextField(blank=True),
        ),
    ]
