# Generated by Django 4.2.29 on 2026-03-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0081_crf7_qui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf7',
            name='qui',
        ),
    ]
