# Generated by Django 4.2.29 on 2026-03-29 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0082_remove_crf7_qui'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='abs_basophils',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_eosinophils',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_lymphocytes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_lymphocytes_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_monocytes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_neutrophil',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_neutrophil_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='bilirubin_direct_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='bilirubin_total_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='cancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf4',
            name='chest_specify',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='chest_xray',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf4',
            name='crf4_cmpltd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='crp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ct_chest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ct_chest_specify',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='d_dimer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ferritin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='hb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='hb_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='hct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ldh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_albumin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_albumin_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alp_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alt_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ast',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ast_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_direct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_direct_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_total_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ggt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_inr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_inr_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_pt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_pt_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ptt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ptt_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mcv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='patient_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf4',
            name='plt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='plt_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='prostate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbg_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbg_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_creatinine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_creatinine_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_creatinine_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_egfr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_egfr_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_egfr_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_urea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_urea_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='sample_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf4',
            name='ultrasound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ultrasound_specify',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='wbc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='wbc_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf6',
            name='clinician_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf6',
            name='completed120days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='outcome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='primary_cause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='reported_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='secondary_cause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='terminate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='terminated_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='today_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
