# Generated by Django 4.2.29 on 2026-03-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0083_crf4_abs_basophils_crf4_abs_eosinophils_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf4',
            old_name='comments',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='adherence',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='medication_given',
        ),
    ]
