# Generated by Django 4.2.29 on 2026-03-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0084_rename_comments_crf4_remarks_remove_crf4_adherence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf4',
            name='crf4_cmpltd_date',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='patient_id',
        ),
    ]
