# Generated by Django 4.2.29 on 2026-03-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0086_remove_crf4_abs_basophils_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='reason',
            field=models.CharField(choices=[('completed', 'Completed Study'), ('ltf', 'Lost To Follow Up'), ('withdrawn', 'Participant Withdrew'), ('transfer_out', 'Transferred Out'), ('medical_reason', 'Medical Reason')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
