# Generated by Django 4.2.29 on 2026-03-31 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('herbal', '0087_crf6_reason'), ('herbal', '0088_crf5_after_visit'), ('herbal', '0089_crf4_abs_basophils_crf4_abs_eosinophils_and_more'), ('herbal', '0090_crf4_renal_urea_grade'), ('herbal', '0091_crf4_liver_ggt_grade'), ('herbal', '0092_crf4_crp_grade_crf4_d_dimer_grade_and_more'), ('herbal', '0093_crf4_rbc_grade'), ('herbal', '0094_crf4_htc_grade'), ('herbal', '0095_rename_htc_grade_crf4_hct_grade'), ('herbal', '0096_crf4_abs_basophils_grade_crf4_abs_eosinophils_grade_and_more'), ('herbal', '0097_alter_crf4_abs_basophils_grade_and_more'), ('herbal', '0098_alter_crf4_abs_basophils_alter_crf4_abs_eosinophils_and_more'), ('herbal', '0099_alter_crf4_cancer_alter_crf4_prostate'), ('herbal', '0100_crf4_chest_xray1'), ('herbal', '0101_crf4_ct_chest1_crf4_ultrasound1'), ('herbal', '0102_remove_crf4_chest_xray_remove_crf4_ct_chest_and_more'), ('herbal', '0103_rename_chest_xray1_crf4_chest_xray'), ('herbal', '0104_rename_ct_chest1_crf4_ct_chest_and_more'), ('herbal', '0105_alter_crf4_chest_xray_alter_crf4_ct_chest_and_more'), ('herbal', '0106_crf4_cancer_test_crf4_prostate_test'), ('herbal', '0107_alter_crf4_chest_specify_alter_crf4_ct_chest_specify_and_more'), ('herbal', '0108_crf5_action_taken_crf5_event_description_and_more'), ('herbal', '0109_crf5_ae_category_crf5_ae_date_crf5_ae_description_and_more'), ('herbal', '0110_crf5_date_reported'), ('herbal', '0111_remove_crf5_event_date'), ('herbal', '0112_remove_crf5_event_description'), ('herbal', '0113_remove_crf5_ae_ongoing'), ('herbal', '0114_crf5_ae_ongoing'), ('herbal', '0115_remove_crf5_ae_outcome_remove_crf5_ae_severity'), ('herbal', '0116_crf5_ae_outcome_crf5_ae_severity'), ('herbal', '0117_remove_crf5_ae_expected_remove_crf5_ae_serious'), ('herbal', '0118_crf5_ae_expected_crf5_ae_serious'), ('herbal', '0119_remove_crf5_ae_relationship_and_more'), ('herbal', '0120_crf5_ae_relationship_crf5_ae_staff_initial_and_more'), ('herbal', '0121_remove_crf5_outcome'), ('herbal', '0122_remove_crf5_action_taken'), ('herbal', '0123_rename_ae_taken_crf5_ae_action_taken'), ('herbal', '0124_remove_crf5_severity'), ('herbal', '0125_rename_ae_staff_initial_crf5_ae_staff'), ('herbal', '0126_crf5_ae_category1'), ('herbal', '0127_remove_crf5_ae_category'), ('herbal', '0128_rename_ae_category1_crf5_ae_category'), ('herbal', '0129_alter_crf5_ae_action_taken_alter_crf5_ae_category_and_more'), ('herbal', '0130_crf6_clinician_name_crf6_comments_and_more'), ('herbal', '0131_alter_crf1chemotherapy_chemotherapy_frequency'), ('herbal', '0132_remove_crf6_completed120days_and_more'), ('herbal', '0133_crf6_completed120days_crf6_terminate_date'), ('herbal', '0134_crf6_completed120days22')]

    dependencies = [
        ('choices', '0022_donenotdone'),
        ('herbal', '0086_remove_crf4_abs_basophils_and_more'),
        ('choices', '0021_grade'),
        ('accounts', '0003_staffprofile_middle_name_prefix_position_and_more'),
        ('choices', '0024_aetreatment_aeseverity_aerelationship_aeoutcome_and_more'),
        ('choices', '0023_alter_donenotdone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='reason',
            field=models.CharField(choices=[('completed', 'Completed Study'), ('ltf', 'Lost To Follow Up'), ('withdrawn', 'Participant Withdrew'), ('transfer_out', 'Transferred Out'), ('medical_reason', 'Medical Reason')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf5',
            name='after_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_after', to='herbal.visitschedule'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_direct_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_total_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbg_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_creatinine_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_egfr_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_urea_units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_basophils_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_basophils_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_eosinophils_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_eosinophils_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_lymphocytes_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_lymphocytes_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_monocytes_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_monocytes_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_neutrophil_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_neutrophil_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='bilirubin_direct_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilirubin_direct_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='bilirubin_total_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilirubin_total_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='crp_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crp_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='d_dimer_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_dimer_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ferritin_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferritin_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='hb_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hb_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='hct_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hct_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ldh_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldh_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_albumin_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_albumin_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alp_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_alp_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_alt_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ast_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_ast_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ggt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_ggt_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_inr_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_inr_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_pt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_pt_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ptt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_ptt_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mch_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mch_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mcv_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcv_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='plt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plt_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbc_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbc_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbg_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbg_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_creatinine_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renal_creatinine_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_egfr_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renal_egfr_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_urea_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renal_urea_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='wbc_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbc_grades', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_basophils',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_eosinophils',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_lymphocytes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_monocytes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_neutrophil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='crp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='d_dimer',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ferritin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='hb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='hct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ldh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_albumin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_alt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ast',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_direct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_bilirubin_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ggt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_pt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='liver_ptt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mcv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='plt',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='rbg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_egfr',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='renal_urea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='wbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='cancer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='prostate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='crf4',
            name='chest_xray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ct_chest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ultrasound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='cancer_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.donenotdone'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='prostate_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.donenotdone'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='chest_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ct_chest_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ultrasound_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='date_reported',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='event_date',
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_ongoing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_expected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_action_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeactiontaken'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aecategory'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeoutcome'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aerelationship'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_serious',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeseverity'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeseverity'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'site__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aetreatment'),
        ),
        migrations.AddField(
            model_name='crf6',
            name='clinician_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf6',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='outcome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='primary_cause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='reported_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='secondary_cause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='terminated_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='today_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crf1chemotherapy',
            name='chemotherapy_frequency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='crf6',
            name='completed120days1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='crf6',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='completed120days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='terminate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='completed120days22',
            field=models.BooleanField(default=False),
        ),
    ]
