# Generated by Django 4.2.29 on 2026-03-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0087_crf6_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='after_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_after', to='herbal.visitschedule'),
        ),
    ]
