# Generated by Django 4.2.29 on 2026-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0089_crf4_abs_basophils_crf4_abs_eosinophils_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='renal_urea_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
