# Generated by Django 4.2.29 on 2026-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0090_crf4_renal_urea_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='liver_ggt_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
