# Generated by Django 4.2.29 on 2026-03-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0091_crf4_liver_ggt_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='crp_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='d_dimer_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ferritin_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ldh_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
