# Generated by Django 4.2.29 on 2026-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0092_crf4_crp_grade_crf4_d_dimer_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='rbc_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
