# Generated by Django 4.2.29 on 2026-03-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0093_crf4_rbc_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='htc_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
