# Generated by Django 4.2.29 on 2026-03-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0094_crf4_htc_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf4',
            old_name='htc_grade',
            new_name='hct_grade',
        ),
    ]
