# Generated by Django 4.2.29 on 2026-03-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0095_rename_htc_grade_crf4_hct_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='abs_basophils_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_eosinophils_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='abs_monocytes_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mch_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='crf4',
            name='mcv_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
