# Generated by Django 4.2.29 on 2026-03-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0021_grade'),
        ('herbal', '0096_crf4_abs_basophils_grade_crf4_abs_eosinophils_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf4',
            name='abs_basophils_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_basophils_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='abs_eosinophils_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_eosinophils_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='abs_lymphocytes_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_lymphocytes_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='abs_monocytes_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_monocytes_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='abs_neutrophil_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abs_neutrophil_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='bilirubin_direct_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilirubin_direct_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='bilirubin_total_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilirubin_total_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='crp_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crp_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='d_dimer_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_dimer_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='ferritin_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferritin_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='hb_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hb_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='hct_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hct_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='ldh_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldh_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_albumin_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_albumin_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_alp_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_alp_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_alt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_alt_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_ast_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_ast_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_ggt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_ggt_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_inr_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_inr_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_pt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_pt_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='liver_ptt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liver_ptt_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='mch_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mch_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='mcv_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcv_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='plt_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plt_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='rbc_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbc_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='rbg_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbg_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='renal_creatinine_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renal_creatinine_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='renal_egfr_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renal_egfr_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='renal_urea_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renal_urea_grades', to='choices.grade'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='wbc_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbc_grades', to='choices.grade'),
        ),
    ]
