# Generated by Django 4.2.29 on 2026-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0098_alter_crf4_abs_basophils_alter_crf4_abs_eosinophils_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf4',
            name='cancer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='prostate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
