# Generated by Django 4.2.29 on 2026-03-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0021_grade'),
        ('herbal', '0100_crf4_chest_xray1'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='ct_chest1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.grade'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='ultrasound1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.grade'),
        ),
    ]
