# Generated by Django 4.2.29 on 2026-03-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0101_crf4_ct_chest1_crf4_ultrasound1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf4',
            name='chest_xray',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='ct_chest',
        ),
        migrations.RemoveField(
            model_name='crf4',
            name='ultrasound',
        ),
    ]
