# Generated by Django 4.2.29 on 2026-03-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0102_remove_crf4_chest_xray_remove_crf4_ct_chest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf4',
            old_name='chest_xray1',
            new_name='chest_xray',
        ),
    ]
