# Generated by Django 4.2.29 on 2026-03-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0103_rename_chest_xray1_crf4_chest_xray'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf4',
            old_name='ct_chest1',
            new_name='ct_chest',
        ),
        migrations.RenameField(
            model_name='crf4',
            old_name='ultrasound1',
            new_name='ultrasound',
        ),
    ]
