# Generated by Django 4.2.29 on 2026-03-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0021_grade'),
        ('herbal', '0104_rename_ct_chest1_crf4_ct_chest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf4',
            name='chest_xray',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='ct_chest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='ultrasound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.appearance'),
        ),
    ]
