# Generated by Django 4.2.29 on 2026-03-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0022_donenotdone'),
        ('herbal', '0105_alter_crf4_chest_xray_alter_crf4_ct_chest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf4',
            name='cancer_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.donenotdone'),
        ),
        migrations.AddField(
            model_name='crf4',
            name='prostate_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.donenotdone'),
        ),
    ]
