# Generated by Django 4.2.29 on 2026-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0106_crf4_cancer_test_crf4_prostate_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf4',
            name='chest_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='ct_chest_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crf4',
            name='ultrasound_specify',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
