# Generated by Django 4.2.29 on 2026-03-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0107_alter_crf4_chest_specify_alter_crf4_ct_chest_specify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='action_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='event_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf5',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
