# Generated by Django 4.2.29 on 2026-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0108_crf5_action_taken_crf5_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='ae_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_expected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_serious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_staff_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf5',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
