# Generated by Django 4.2.29 on 2026-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0109_crf5_ae_category_crf5_ae_date_crf5_ae_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='date_reported',
            field=models.DateField(blank=True, null=True),
        ),
    ]
