# Generated by Django 4.2.29 on 2026-03-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0110_crf5_date_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='event_date',
        ),
    ]
