# Generated by Django 4.2.29 on 2026-03-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0111_remove_crf5_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='event_description',
        ),
    ]
