# Generated by Django 4.2.29 on 2026-03-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0112_remove_crf5_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='ae_ongoing',
        ),
    ]
