# Generated by Django 4.2.29 on 2026-03-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0114_crf5_ae_ongoing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='ae_outcome',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='ae_severity',
        ),
    ]
