# Generated by Django 4.2.29 on 2026-03-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0116_crf5_ae_outcome_crf5_ae_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='ae_expected',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='ae_serious',
        ),
    ]
