# Generated by Django 4.2.29 on 2026-03-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0023_alter_donenotdone_options'),
        ('herbal', '0117_remove_crf5_ae_expected_remove_crf5_ae_serious'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='ae_expected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AddField(
            model_name='crf5',
            name='ae_serious',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
    ]
