# Generated by Django 4.2.29 on 2026-03-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0118_crf5_ae_expected_crf5_ae_serious'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='ae_relationship',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='ae_staff_initial',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='ae_taken',
        ),
        migrations.RemoveField(
            model_name='crf5',
            name='ae_treatment',
        ),
    ]
