# Generated by Django 4.2.29 on 2026-03-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0120_crf5_ae_relationship_crf5_ae_staff_initial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='outcome',
        ),
    ]
