# Generated by Django 4.2.29 on 2026-03-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0121_remove_crf5_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='action_taken',
        ),
    ]
