# Generated by Django 4.2.29 on 2026-03-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0122_remove_crf5_action_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf5',
            old_name='ae_taken',
            new_name='ae_action_taken',
        ),
    ]
