# Generated by Django 4.2.29 on 2026-03-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0123_rename_ae_taken_crf5_ae_action_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='severity',
        ),
    ]
