# Generated by Django 4.2.29 on 2026-03-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0124_remove_crf5_severity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf5',
            old_name='ae_staff_initial',
            new_name='ae_staff',
        ),
    ]
