# Generated by Django 4.2.29 on 2026-03-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0024_aetreatment_aeseverity_aerelationship_aeoutcome_and_more'),
        ('herbal', '0125_rename_ae_staff_initial_crf5_ae_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf5',
            name='ae_category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
    ]
