# Generated by Django 4.2.29 on 2026-03-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0126_crf5_ae_category1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='ae_category',
        ),
    ]
