# Generated by Django 4.2.29 on 2026-03-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0127_remove_crf5_ae_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf5',
            old_name='ae_category1',
            new_name='ae_category',
        ),
    ]
