# Generated by Django 4.2.29 on 2026-03-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0024_aetreatment_aeseverity_aerelationship_aeoutcome_and_more'),
        ('accounts', '0003_staffprofile_middle_name_prefix_position_and_more'),
        ('herbal', '0128_rename_ae_category1_crf5_ae_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf5',
            name='ae_action_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeactiontaken'),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='ae_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aecategory'),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='ae_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeoutcome'),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='ae_relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aerelationship'),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='ae_serious',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeseverity'),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='ae_severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aeseverity'),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='ae_staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'site__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile'),
        ),
        migrations.AlterField(
            model_name='crf5',
            name='ae_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.aetreatment'),
        ),
    ]
