# Generated by Django 4.2.29 on 2026-03-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0129_alter_crf5_ae_action_taken_alter_crf5_ae_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='clinician_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crf6',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='completed120days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='date_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='outcome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='outcome_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='primary_cause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='reported_dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='secondary_cause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='terminate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='terminated_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='today_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
