# Generated by Django 4.2.29 on 2026-03-31 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0130_crf6_clinician_name_crf6_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crf1chemotherapy',
            name='chemotherapy_frequency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
