# Generated by Django 4.2.29 on 2026-03-31 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0024_aetreatment_aeseverity_aerelationship_aeoutcome_and_more'),
        ('herbal', '0131_alter_crf1chemotherapy_chemotherapy_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='completed120days',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='terminate_date',
        ),
        migrations.AddField(
            model_name='crf6',
            name='completed120days1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
        migrations.AlterField(
            model_name='crf6',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
