# Generated by Django 4.2.29 on 2026-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0132_remove_crf6_completed120days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='completed120days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crf6',
            name='terminate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
