# Generated by Django 4.2.29 on 2026-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0133_crf6_completed120days_crf6_terminate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='completed120days22',
            field=models.BooleanField(default=False),
        ),
    ]
