# Generated by Django 4.2.29 on 2026-03-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0024_aetreatment_aeseverity_aerelationship_aeoutcome_and_more'),
        ('herbal', '0087_crf6_reason_squashed_0134_crf6_completed120days22'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='completed120days2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.yesnounk'),
        ),
    ]
