# Generated by Django 4.2.29 on 2026-03-31 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0136_remove_crf6_completed120days1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='terminate_date',
        ),
    ]
