# Generated by Django 4.2.29 on 2026-03-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0137_remove_crf6_terminate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='reported_dead1',
            field=models.BooleanField(default=False),
        ),
    ]
