# Generated by Django 4.2.29 on 2026-03-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0138_crf6_reported_dead1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='reported_dead',
        ),
    ]
