# Generated by Django 4.2.29 on 2026-03-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0143_crf6_withdrew_consent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf6',
            old_name='comments',
            new_name='remarks',
        ),
    ]
