# Generated by Django 4.2.29 on 2026-03-31 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0144_rename_comments_crf6_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf6',
            old_name='terminated_reason',
            new_name='termination_reason',
        ),
    ]
