# Generated by Django 4.2.29 on 2026-03-31 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0026_terminationreason'),
        ('herbal', '0145_rename_terminated_reason_crf6_termination_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='termination_reason1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.terminationreason'),
        ),
    ]
