# Generated by Django 4.2.29 on 2026-03-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0146_crf6_termination_reason1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='termination_reason',
        ),
    ]
