# Generated by Django 4.2.29 on 2026-03-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0147_remove_crf6_termination_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf6',
            old_name='termination_reason1',
            new_name='termination_reason',
        ),
    ]
