# Generated by Django 4.2.29 on 2026-03-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0148_rename_termination_reason1_crf6_termination_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='reason',
        ),
    ]
