# Generated by Django 4.2.29 on 2026-03-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0149_remove_crf6_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='clinician_name',
        ),
    ]
