# Generated by Django 4.2.29 on 2026-03-31 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile_middle_name_prefix_position_and_more'),
        ('herbal', '0150_remove_crf6_clinician_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='clinician_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'site__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile'),
        ),
    ]
