# Generated by Django 4.2.29 on 2026-03-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0151_crf6_clinician_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf6',
            old_name='termination_reason',
            new_name='reason',
        ),
    ]
