# Generated by Django 4.2.29 on 2026-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0152_rename_termination_reason_crf6_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='outcome1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
