# Generated by Django 4.2.29 on 2026-04-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0153_crf6_outcome1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='outcome',
        ),
    ]
