# Generated by Django 4.2.29 on 2026-04-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0155_crf6_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='outcome1',
        ),
    ]
