# Generated by Django 4.2.29 on 2026-04-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0026_terminationreason'),
        ('herbal', '0156_remove_crf6_outcome1'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='withdrew_reason1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.outcome'),
        ),
    ]
