# Generated by Django 4.2.29 on 2026-04-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0157_crf6_withdrew_reason1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='withdrew_reason',
        ),
    ]
