# Generated by Django 4.2.29 on 2026-04-01 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0026_terminationreason'),
        ('herbal', '0158_remove_crf6_withdrew_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf6',
            name='withdrew_reason1',
        ),
        migrations.AddField(
            model_name='crf6',
            name='withdrew_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='choices.withdrewreason'),
        ),
    ]
