# Generated by Django 4.2.29 on 2026-04-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0159_remove_crf6_withdrew_reason1_crf6_withdrew_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf7',
            name='cdate',
        ),
        migrations.RemoveField(
            model_name='crf7',
            name='fdate',
        ),
    ]
