# Generated by Django 4.2.29 on 2026-04-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0160_remove_crf7_cdate_remove_crf7_fdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crf6',
            name='outcome_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crf6',
            name='reason_other',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crf6',
            name='withdrew_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
