# Generated by Django 4.2.29 on 2026-04-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0161_crf6_outcome_other_crf6_reason_other_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crf6',
            old_name='date_death',
            new_name='reason_date',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='completed120days',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='reported_dead',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='crf6',
            name='withdrew_consent',
        ),
    ]
