# Generated by Django 4.2.29 on 2026-04-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0162_rename_date_death_crf6_reason_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crf5',
            name='ae_date',
        ),
    ]
