# Generated by Django 4.2.29 on 2026-04-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0163_remove_crf5_ae_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
