# Generated by Django 4.2.29 on 2026-04-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal', '0164_visitschedule_last_reminder_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
