# Generated by Django 4.2.29 on 2026-03-19 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_district_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='locations.ward')),
            ],
        ),
    ]
