# Generated by Django 4.2.29 on 2026-03-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_street'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('ward', 'name')},
        ),
    ]
