# Generated by Django 4.2.29 on 2026-03-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_street_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['code']},
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together=set(),
        ),
    ]
