# Generated by Django 4.2.29 on 2026-03-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_district_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='ward',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('ward', 'name')},
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='locations_d_name_f8f0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'name'], name='locations_d_region__c0ced9_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='locations_r_name_e5c9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['name'], name='locations_s_name_7c101e_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['ward', 'name'], name='locations_s_ward_id_f8c944_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['name'], name='locations_w_name_ab5e40_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['district', 'name'], name='locations_w_distric_90b274_idx'),
        ),
    ]
