# Generated by Django 4.2.29 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_district_label_district_value_region_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
