# Generated by Django 4.2.20 on 2025-08-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManual',
        ),
    ]
