# Generated by Django 4.2.20 on 2025-07-29 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0001_initial'),
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.site')),
            ],
        ),
        migrations.CreateModel(
            name='VisitDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='mentorship.visit')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('visit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AssignedCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competences_assigned', to=settings.AUTH_USER_MODEL)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.competence')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.disease')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_competencies', to=settings.AUTH_USER_MODEL)),
                ('visit_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mentorship.visitday')),
            ],
            options={
                'unique_together': {('visit_day', 'mentee', 'competence')},
            },
        ),
    ]
