# Generated by Django 4.2.20 on 2025-07-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_visit_visitday_assignedcompetence'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcompetence',
            name='mentee_self_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignedcompetence',
            name='mentor_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
