# Generated by Django 4.2.20 on 2025-08-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_assignedcompetence_mentor_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcompetence',
            old_name='mentee_self_grade',
            new_name='mentee_grade',
        ),
        migrations.RenameField(
            model_name='assignedcompetence',
            old_name='remarks',
            new_name='mentee_remarks',
        ),
    ]
