# Generated by Django 4.2.20 on 2025-08-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0006_rename_mentee_self_grade_assignedcompetence_mentee_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcompetence',
            name='is_self_assessed',
        ),
    ]
