# Generated by Django 4.2.29 on 2026-03-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_site_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
