# Generated by Django 4.2.20 on 2025-07-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_assignedcompetence_mentee_self_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcompetence',
            name='is_self_assessed',
            field=models.BooleanField(default=False),
        ),
    ]
