# Generated by Django 4.2.20 on 2025-07-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_assignedcompetence_is_self_assessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcompetence',
            name='mentor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
